language: objective-c

osx_image: xcode7.3

before_install:
   - rvm use system
   - sudo gem install bundler
   - sudo gem install cocoapods -v '1.0.1'

script:
   xcodebuild -workspace FetchedResultsController.xcworkspace -scheme FetchedResultsController test -destination 'platform=iOS Simulator,name=iPhone 6'
